// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/home/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/home/AppHeader.vue')['default']
    ConnectionLost: typeof import('./src/components/ConnectionLost.vue')['default']
    CookieModal: typeof import('./src/components/CookieModal.vue')['default']
    ErrorContainer: typeof import('./src/components/ErrorContainer.vue')['default']
    FaqSection: typeof import('./src/components/home/FaqSection.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QFooter: typeof import('quasar')['QFooter']
    QHeader: typeof import('quasar')['QHeader']
    QLayout: typeof import('quasar')['QLayout']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    TeamSection: typeof import('./src/components/home/TeamSection.vue')['default']
    TelegramSvg: typeof import('./src/components/icons/TelegramSvg.vue')['default']
    TwitterSvg: typeof import('./src/components/icons/TwitterSvg.vue')['default']
  }
}

export { }
