// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Apy: typeof import('./../src/components/staking/Apy.vue')['default']
    ClusterSelector: typeof import('./../src/components/staking/ClusterSelector.vue')['default']
    ConnectionLost: typeof import('./../src/components/ConnectionLost.vue')['default']
    ConnectWallet: typeof import('./../src/components/staking/ConnectWallet.vue')['default']
    CookieModal: typeof import('./../src/components/CookieModal.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    Epoch: typeof import('./../src/components/staking/Epoch.vue')['default']
    ErrorContainer: typeof import('./../src/components/ErrorContainer.vue')['default']
    KiwiLink: typeof import('./../src/components/staking/KiwiLink.vue')['default']
    MainSection: typeof import('./../src/components/staking/MainSection.vue')['default']
    RoiCalculatorBtn: typeof import('./../src/components/staking/RoiCalculatorBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolSvg: typeof import('./../src/components/icons/SolSvg.vue')['default']
    StakeBox: typeof import('./../src/components/staking/stake/StakeBox.vue')['default']
    StakeSuccessDialog: typeof import('./../src/components/staking/stake/StakeSuccessDialog.vue')['default']
    ThemeModeSelector: typeof import('./../src/components/ThemeModeSelector.vue')['default']
    TotalStacked: typeof import('./../src/components/staking/TotalStacked.vue')['default']
    WrongVoter: typeof import('./../src/components/WrongVoter.vue')['default']
  }
}

export {}
