name: Production Build and Deploy
on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#    paths-ignore:
#      - '.github/workflows/**'
#      - '**.md'
env:
  REPO: mfactory-lab/staking_kiwi_prod
  URL: staking.kiwi

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Build
        run: |
          cd build
          yarn
          yarn build:staging
          cd ..

      - name: Checkout Prod Target
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO }}
          path: 'deploy'
          token: ${{ secrets.PAT }}

      - name: Push files to target
        run: |
          cp -r build/dist/* deploy
          cd deploy
          echo ${{ env.URL }} > CNAME
          cp index.html 404.html
          git add .
          git commit -m $GITHUB_SHA
          git push
