name: Development Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  URL: widget.staking.kiwi

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://${{ env.URL }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'build'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Build
        run: |
          cd build
          pnpm install
          pnpm build:staging
          cp dist/index.html dist/404.html
          echo ${{ env.URL }} > dist/CNAME
          pnpm run deploy:gh-pages